import { isToday } from 'date-fns';
import Head from 'next/head';
import { useCalendar } from '../hooks/useCalendar';

export default function Home() {
  const calendar = useCalendar();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
        <div>
          <h1>Calendar</h1>
          <h4>{calendar.currentYear}</h4>
          <h4>{calendar.currentMonth}</h4>
          <button onClick={calendar?.setPreviousMonth}>Previous month</button>
          <button onClick={calendar?.setNextMonth}>Next month</button>
          {calendar.month.map((week, index) => {
            return (
              <div key={index}>
                {week.map((day, j) => (
                  <span
                    key={j}
                    style={{
                      width: 100,
                      height: 100,
                      padding: 10,
                      fontSize: 16,
                      border: '1px white solid',
                      display: 'inline-block',
                      backgroundColor: isToday(day) ? 'gray' : 'black',
                    }}
                  >
                    {day.getDate()}
                  </span>
                ))}
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
