import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useCalendar } from '../hooks/useCalendar';

const ClientCalendar = dynamic(() => import('../components/Calendar'), { ssr: false });

export default function Home() {
  const calendar = useCalendar();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
        <ClientCalendar calendar={calendar} />
      </main>
    </>
  );
}
